import "./globals.css";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata =
{
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<
{
	children: React.ReactNode;
}>)
{
	return (
		<html lang="en" className="scroll-smooth">
			<body>
				{children}
				<ToastContainer />
			</body>
		</html>
	);
}
